before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./cmd/slang/
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: zip
    files:
      - LICENSE*
      - README.md
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
